# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_availablecountries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u043e\u0432 \u043f\u043e \u0440\u0435\u0444. \u0441\u0441\u044b\u043b\u043a\u0435')),
                ('signups', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0439 \u043f\u043e \u0440\u0435\u0444. \u0441\u0441\u044b\u043b\u043a\u0435')),
                ('purchases', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u043e\u043a\u0443\u043f\u043e\u043a \u043f\u043e \u0440\u0435\u0444. \u0441\u0441\u044b\u043b\u043a\u0435')),
                ('purchase_amount', models.FloatField(verbose_name='\u0421\u0443\u043c\u043c\u0430\u0440\u043d\u043e\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u0443\u043f\u043b\u0435\u043d\u043d\u044b\u0445 \u0442\u043e\u043a\u0435\u043d\u043e\u0432')),
                ('value', models.FloatField(default=0, verbose_name='\u0412\u0435\u043b\u0438\u0447\u0438\u043d\u0430 \u0431\u043e\u043d\u0443\u0441\u0430 (\u0432 %)')),
                ('bonus_tokens', models.FloatField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0431\u043e\u043d\u0443\u0441\u043d\u044b\u0445 \u0442\u043e\u043a\u0435\u043d\u043e\u0432')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
    ]
