# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180228_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralbonus',
            name='partner_value',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0412\u0435\u043b\u0438\u0447\u0438\u043d\u0430 \u0431\u043e\u043d\u0443\u0441\u0430 \u0434\u043b\u044f \u041f\u0430\u0440\u0442\u043d\u0435\u0440\u0430 (\u0432 %)'),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='purchase_amount',
            field=models.FloatField(default=0, verbose_name='\u0421\u0443\u043c\u043c\u0430\u0440\u043d\u043e\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043a\u0443\u043f\u043b\u0435\u043d\u043d\u044b\u0445 \u0442\u043e\u043a\u0435\u043d\u043e\u0432'),
        ),
    ]
