# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180228_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonusStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.FloatField(default=0, unique=True, verbose_name='\u041f\u043e\u0440\u043e\u0433 \u0441\u043a\u0438\u0434\u043a\u0438 (\u0441 \u043a\u0430\u043a\u043e\u0433\u043e \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u0430 \u0442\u043e\u043a\u0435\u043d\u043e\u0432 \u0431\u0443\u0434\u0435\u0442 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0441\u044f \u044d\u0442\u0430 \u0441\u043a\u0438\u0434\u043a\u0430)')),
                ('value', models.FloatField(default=0, unique=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 (\u0432 %)')),
            ],
            options={
                'verbose_name': 'Referral Bonus Step',
                'verbose_name_plural': 'Referral Bonus Steps',
            },
        ),
    ]
