# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_referralbonusstep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralbonusstep',
            options={'ordering': ('-step',), 'verbose_name': 'Referral Bonus Step', 'verbose_name_plural': 'Referral Bonus Steps'},
        ),
    ]
