# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180228_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a BTC')),
                ('eth', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a ETH')),
                ('xrp', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a XRP')),
                ('bch', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a BCH')),
                ('ada', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a ADA')),
                ('xlm', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a XLM')),
                ('neo', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a NEO')),
                ('ltc', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a LTC')),
                ('eos', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a EOS')),
                ('xem', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a XEM')),
                ('dash', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a DASH')),
                ('etc', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a ETC')),
                ('used_by_user', models.BooleanField(default=False, verbose_name='\u041f\u0440\u0438\u0432\u044f\u0437\u0430\u043d\u043e \u043a \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044e')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_wallets', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': 'Profile Wallets',
                'verbose_name_plural': 'Profile Wallets',
            },
        ),
    ]
