# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profilewallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ada',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a ADA'),
        ),
        migrations.AddField(
            model_name='user',
            name='bch',
            field=models.CharField(blank=True, max_length=48, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a BCH'),
        ),
        migrations.AddField(
            model_name='user',
            name='btc',
            field=models.CharField(blank=True, max_length=48, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a BTC'),
        ),
        migrations.AddField(
            model_name='user',
            name='dash',
            field=models.CharField(blank=True, max_length=48, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a DASH'),
        ),
        migrations.AddField(
            model_name='user',
            name='eos',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a EOS'),
        ),
        migrations.AddField(
            model_name='user',
            name='etc',
            field=models.CharField(blank=True, max_length=48, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a ETC'),
        ),
        migrations.AddField(
            model_name='user',
            name='eth',
            field=models.CharField(blank=True, max_length=48, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a ETH'),
        ),
        migrations.AddField(
            model_name='user',
            name='ltc',
            field=models.CharField(blank=True, max_length=48, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a LTC'),
        ),
        migrations.AddField(
            model_name='user',
            name='neo',
            field=models.CharField(blank=True, max_length=48, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a NEO'),
        ),
        migrations.AddField(
            model_name='user',
            name='xem',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a XEM'),
        ),
        migrations.AddField(
            model_name='user',
            name='xlm',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a XLM'),
        ),
        migrations.AddField(
            model_name='user',
            name='xrp',
            field=models.CharField(blank=True, max_length=48, verbose_name='\u041a\u043e\u0448\u0435\u043b\u0435\u043a XRP'),
        ),
    ]
