# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_ref_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(max_length=5, verbose_name='\u0422\u0438\u043f \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
    ]
