# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20180302_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ref_response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_response', to='referrals.ReferralResponse', verbose_name='Ref purchase'),
        ),
    ]
