# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20171117_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfiguration',
            name='discount_timer',
            field=models.DateField(default='2017-12-31', verbose_name='\u0422\u0430\u0439\u043c\u0435\u0440 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='timer_sale',
            field=models.DateField(default='2017-12-31', verbose_name='\u0422\u0430\u0439\u043c\u0435\u0440'),
        ),
    ]
