# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20171117_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfiguration',
            name='onepager_btn_text',
            field=models.TextField(default='One\npager', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 onepager'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='sale_btn',
            field=models.CharField(default='\u041d\u0410\u0428\u0418\n\u0410\u041a\u0426\u0418\u0418', max_length=32, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='sale_btn_en',
            field=models.CharField(default='\u041d\u0410\u0428\u0418\n\u0410\u041a\u0426\u0418\u0418', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='sale_btn_ru',
            field=models.CharField(default='\u041d\u0410\u0428\u0418\n\u0410\u041a\u0426\u0418\u0418', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='whitepaper_btn_text',
            field=models.TextField(default='White\npaper', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 whitepaper'),
        ),
    ]
