# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20171117_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfiguration',
            name='onepager_link',
            field=models.TextField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 onepager'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='onepager_link_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 onepager'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='onepager_link_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 onepager'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='onepager_upload',
            field=models.FileField(blank=True, upload_to='onepagers', verbose_name='\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c onepager'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='onepager_upload_en',
            field=models.FileField(blank=True, null=True, upload_to='onepagers', verbose_name='\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c onepager'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='onepager_upload_ru',
            field=models.FileField(blank=True, null=True, upload_to='onepagers', verbose_name='\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c onepager'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='sale_btn',
            field=models.TextField(default='\u041d\u0410\u0428\u0418\n\u0410\u041a\u0426\u0418\u0418', max_length=32, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='sale_btn_en',
            field=models.TextField(default='\u041d\u0410\u0428\u0418\n\u0410\u041a\u0426\u0418\u0418', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='sale_btn_ru',
            field=models.TextField(default='\u041d\u0410\u0428\u0418\n\u0410\u041a\u0426\u0418\u0418', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='whitepaper_link',
            field=models.TextField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 whitepaper'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='whitepaper_link_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 whitepaper'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='whitepaper_link_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 whitepaper'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='whitepaper_upload',
            field=models.FileField(blank=True, upload_to='whitepapers', verbose_name='\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c whitepaper'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='whitepaper_upload_en',
            field=models.FileField(blank=True, null=True, upload_to='whitepapers', verbose_name='\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c whitepaper'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='whitepaper_upload_ru',
            field=models.FileField(blank=True, null=True, upload_to='whitepapers', verbose_name='\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c whitepaper'),
        ),
    ]
