# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20171117_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='subscribe_blue_text',
            field=models.TextField(default='companyname', verbose_name='\u0421\u0438\u043d\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='subscribe_blue_text_en',
            field=models.TextField(default='companyname', null=True, verbose_name='\u0421\u0438\u043d\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='subscribe_blue_text_ru',
            field=models.TextField(default='companyname', null=True, verbose_name='\u0421\u0438\u043d\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='subscribe_title',
            field=models.TextField(default='\u041f\u041e\u0414\u041f\u0418\u0428\u0418\u0421\u042c \u041d\u0410 \u041d\u0410\u0428\u0418 \u041d\u041e\u0412\u041e\u0421\u0422\u0418', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0444\u043e\u0440\u043c\u044b'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='subscribe_title_en',
            field=models.TextField(default='\u041f\u041e\u0414\u041f\u0418\u0428\u0418\u0421\u042c \u041d\u0410 \u041d\u0410\u0428\u0418 \u041d\u041e\u0412\u041e\u0421\u0422\u0418', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0444\u043e\u0440\u043c\u044b'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='subscribe_title_ru',
            field=models.TextField(default='\u041f\u041e\u0414\u041f\u0418\u0428\u0418\u0421\u042c \u041d\u0410 \u041d\u0410\u0428\u0418 \u041d\u041e\u0412\u041e\u0421\u0422\u0418', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0444\u043e\u0440\u043c\u044b'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='subscribe_white_text',
            field=models.TextField(default='is a full-featured spot trading platform', verbose_name='\u0411\u0435\u043b\u044b\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='subscribe_white_text_en',
            field=models.TextField(default='is a full-featured spot trading platform', null=True, verbose_name='\u0411\u0435\u043b\u044b\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='subscribe_white_text_ru',
            field=models.TextField(default='is a full-featured spot trading platform', null=True, verbose_name='\u0411\u0435\u043b\u044b\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='onepager_btn_text',
            field=models.TextField(default='Onepager', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 onepager'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='whitepaper_btn_text',
            field=models.TextField(default='Whitepaper', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 whitepaper'),
        ),
    ]
