# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20171117_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block1_text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block1_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block1_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block1_title',
            field=models.TextField(blank=True, help_text='ZNAQ INDEX', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block1_title_en',
            field=models.TextField(blank=True, help_text='ZNAQ INDEX', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block1_title_ru',
            field=models.TextField(blank=True, help_text='ZNAQ INDEX', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block2_text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block2_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block2_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block2_title',
            field=models.TextField(blank=True, help_text='ZNAQ TOKEN', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block2_title_en',
            field=models.TextField(blank=True, help_text='ZNAQ TOKEN', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block2_title_ru',
            field=models.TextField(blank=True, help_text='ZNAQ TOKEN', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block_img',
            field=models.ImageField(blank=True, upload_to='landing_images', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block1_text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u043e\u0432\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043f\u0440\u0430\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block1_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u043e\u0432\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043f\u0440\u0430\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block1_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u043e\u0432\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043f\u0440\u0430\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block2_text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043f\u0440\u0430\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block2_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043f\u0440\u0430\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block2_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430 \u0441\u043f\u0440\u0430\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block_img',
            field=models.ImageField(blank=True, upload_to='landing_images', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block_title',
            field=models.TextField(blank=True, help_text='\u041e\u041f\u0418\u0421\u0410\u041d\u0418\u0415 \u0420\u042b\u041d\u041a\u0410 \u041a\u0420\u0418\u041f\u0422\u041e\u0412\u0410\u041b\u042e\u0422', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 \u0441\u043f\u0440\u0430\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block_title_en',
            field=models.TextField(blank=True, help_text='\u041e\u041f\u0418\u0421\u0410\u041d\u0418\u0415 \u0420\u042b\u041d\u041a\u0410 \u041a\u0420\u0418\u041f\u0422\u041e\u0412\u0410\u041b\u042e\u0422', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 \u0441\u043f\u0440\u0430\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block_title_ru',
            field=models.TextField(blank=True, help_text='\u041e\u041f\u0418\u0421\u0410\u041d\u0418\u0415 \u0420\u042b\u041d\u041a\u0410 \u041a\u0420\u0418\u041f\u0422\u041e\u0412\u0410\u041b\u042e\u0422', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 \u0441\u043f\u0440\u0430\u0432\u0430'),
        ),
    ]
