# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20171118_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block_img1_title_en',
            field=models.TextField(blank=True, help_text='INITIAL INVESTMENT', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block_img1_title_ru',
            field=models.TextField(blank=True, help_text='INITIAL INVESTMENT', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block_img2_title_en',
            field=models.TextField(blank=True, help_text='PURCHASE DATA', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0441\u043b\u0435\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='left_block_img2_title_ru',
            field=models.TextField(blank=True, help_text='PURCHASE DATA', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0441\u043b\u0435\u0432\u0430'),
        ),
    ]
