# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:31
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20171118_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='color',
            field=colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF'], default='#FF0000'),
        ),
    ]
