# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_landingconfiguration_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='color',
        ),
    ]
