# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20171118_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_percent1',
            field=models.CharField(default='60%', max_length=10, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_percent2',
            field=models.CharField(default='15%', max_length=10, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_percent3',
            field=models.CharField(default='10%', max_length=10, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_percent4',
            field=models.CharField(default='10%', max_length=10, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_percent5',
            field=models.CharField(default='5%', max_length=10, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text1',
            field=models.TextField(default='ICO', verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text1_en',
            field=models.TextField(default='ICO', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text1_ru',
            field=models.TextField(default='ICO', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text2',
            field=models.TextField(default='Team', verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text2_en',
            field=models.TextField(default='Team', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text2_ru',
            field=models.TextField(default='Team', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text3',
            field=models.TextField(default='Company', verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text3_en',
            field=models.TextField(default='Company', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text3_ru',
            field=models.TextField(default='Company', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text4',
            field=models.TextField(default='Marketing', verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text4_en',
            field=models.TextField(default='Marketing', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text4_ru',
            field=models.TextField(default='Marketing', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text5',
            field=models.TextField(default='Bounty', verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text5_en',
            field=models.TextField(default='Bounty', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_text5_ru',
            field=models.TextField(default='Bounty', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_title',
            field=models.TextField(default='\u0420\u0410\u0421\u041f\u0420\u0415\u0414\u0415\u041b\u0415\u041d\u0418\u0415 \u0422\u041e\u041a\u0415\u041d\u041e\u0412', verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u0420\u0430\u0441\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u0438\u0435 \u0442\u043e\u043a\u0435\u043d\u043e\u0432'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_title_en',
            field=models.TextField(default='\u0420\u0410\u0421\u041f\u0420\u0415\u0414\u0415\u041b\u0415\u041d\u0418\u0415 \u0422\u041e\u041a\u0415\u041d\u041e\u0412', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u0420\u0430\u0441\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u0438\u0435 \u0442\u043e\u043a\u0435\u043d\u043e\u0432'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='tokens_title_ru',
            field=models.TextField(default='\u0420\u0410\u0421\u041f\u0420\u0415\u0414\u0415\u041b\u0415\u041d\u0418\u0415 \u0422\u041e\u041a\u0415\u041d\u041e\u0412', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u0420\u0430\u0441\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u0438\u0435 \u0442\u043e\u043a\u0435\u043d\u043e\u0432'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_percent1',
            field=models.CharField(default='6%', max_length=10, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_percent2',
            field=models.CharField(default='8%', max_length=10, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_percent3',
            field=models.CharField(default='20%', max_length=10, verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_percent4',
            field=models.CharField(default='11%', max_length=10, verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_percent5',
            field=models.CharField(default='6%', max_length=10, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_percent6',
            field=models.CharField(default='16%', max_length=10, verbose_name='\u0428\u0435\u0441\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_percent7',
            field=models.CharField(default='19%', max_length=10, verbose_name='\u0421\u0435\u0434\u044c\u043c\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_percent8',
            field=models.CharField(default='14%', max_length=10, verbose_name='\u0412\u043e\u0441\u044c\u043c\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text1',
            field=models.TextField(default='\u041e\u043f\u0435\u0440\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b', verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text1_en',
            field=models.TextField(default='\u041e\u043f\u0435\u0440\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text1_ru',
            field=models.TextField(default='\u041e\u043f\u0435\u0440\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b', null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text2',
            field=models.TextField(default='Office expenses', verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text2_en',
            field=models.TextField(default='Office expenses', null=True, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text2_ru',
            field=models.TextField(default='Office expenses', null=True, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text3',
            field=models.TextField(default='\u0411\u0438\u0440\u0436\u0430', verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text3_en',
            field=models.TextField(default='\u0411\u0438\u0440\u0436\u0430', null=True, verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text3_ru',
            field=models.TextField(default='\u0411\u0438\u0440\u0436\u0430', null=True, verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text4',
            field=models.TextField(default='\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433', verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text4_en',
            field=models.TextField(default='\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433', null=True, verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text4_ru',
            field=models.TextField(default='\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433', null=True, verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text5',
            field=models.TextField(default='Legal', verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text5_en',
            field=models.TextField(default='Legal', null=True, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text5_ru',
            field=models.TextField(default='Legal', null=True, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text6',
            field=models.TextField(default='\u0417\u0430\u043f\u0443\u0441\u043a \u043d\u043e\u0432\u044b\u0445 \u0438\u043d\u0434\u0435\u043a\u0441\u043e\u0432', verbose_name='\u0428\u0435\u0441\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text6_en',
            field=models.TextField(default='\u0417\u0430\u043f\u0443\u0441\u043a \u043d\u043e\u0432\u044b\u0445 \u0438\u043d\u0434\u0435\u043a\u0441\u043e\u0432', null=True, verbose_name='\u0428\u0435\u0441\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text6_ru',
            field=models.TextField(default='\u0417\u0430\u043f\u0443\u0441\u043a \u043d\u043e\u0432\u044b\u0445 \u0438\u043d\u0434\u0435\u043a\u0441\u043e\u0432', null=True, verbose_name='\u0428\u0435\u0441\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text7',
            field=models.TextField(default='\u0420\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0430 \u0435\u0434\u0438\u043d\u043e\u0439 \u0441\u0438\u0441\u0442\u0435\u043c\u044b \u0442\u043e\u0440\u0433\u043e\u0432 ZNAQ', verbose_name='\u0421\u0435\u0434\u044c\u043c\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text7_en',
            field=models.TextField(default='\u0420\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0430 \u0435\u0434\u0438\u043d\u043e\u0439 \u0441\u0438\u0441\u0442\u0435\u043c\u044b \u0442\u043e\u0440\u0433\u043e\u0432 ZNAQ', null=True, verbose_name='\u0421\u0435\u0434\u044c\u043c\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text7_ru',
            field=models.TextField(default='\u0420\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0430 \u0435\u0434\u0438\u043d\u043e\u0439 \u0441\u0438\u0441\u0442\u0435\u043c\u044b \u0442\u043e\u0440\u0433\u043e\u0432 ZNAQ', null=True, verbose_name='\u0421\u0435\u0434\u044c\u043c\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text8',
            field=models.TextField(default='\u0410\u043d\u0430\u043b\u0438\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u043a\u043b\u0443\u0431 \u0434\u043b\u044f \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0435\u0432 ZNAQ Token', verbose_name='\u0412\u043e\u0441\u044c\u043c\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text8_en',
            field=models.TextField(default='\u0410\u043d\u0430\u043b\u0438\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u043a\u043b\u0443\u0431 \u0434\u043b\u044f \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0435\u0432 ZNAQ Token', null=True, verbose_name='\u0412\u043e\u0441\u044c\u043c\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text8_ru',
            field=models.TextField(default='\u0410\u043d\u0430\u043b\u0438\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u043a\u043b\u0443\u0431 \u0434\u043b\u044f \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0435\u0432 ZNAQ Token', null=True, verbose_name='\u0412\u043e\u0441\u044c\u043c\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_title',
            field=models.TextField(default='\u0420\u0410\u0421\u041f\u0420\u0415\u0414\u0415\u041b\u0415\u041d\u0418\u0415 \u0421\u0420\u0415\u0414\u0421\u0422\u0412', verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u0420\u0430\u0441\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u0438\u0435 \u0441\u0440\u0435\u0434\u0441\u0442\u0432'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_title_en',
            field=models.TextField(default='\u0420\u0410\u0421\u041f\u0420\u0415\u0414\u0415\u041b\u0415\u041d\u0418\u0415 \u0421\u0420\u0415\u0414\u0421\u0422\u0412', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u0420\u0430\u0441\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u0438\u0435 \u0441\u0440\u0435\u0434\u0441\u0442\u0432'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_title_ru',
            field=models.TextField(default='\u0420\u0410\u0421\u041f\u0420\u0415\u0414\u0415\u041b\u0415\u041d\u0418\u0415 \u0421\u0420\u0415\u0414\u0421\u0422\u0412', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u0420\u0430\u0441\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u0438\u0435 \u0441\u0440\u0435\u0434\u0441\u0442\u0432'"),
        ),
    ]
