# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_auto_20171118_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_percent2',
            field=models.CharField(default='15%', max_length=10, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_percent3',
            field=models.CharField(default='10%', max_length=10, verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_percent4',
            field=models.CharField(default='10%', max_length=10, verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_percent5',
            field=models.CharField(default='5%', max_length=10, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (%)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text2',
            field=models.TextField(default='Team', verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text2_en',
            field=models.TextField(default='Team', null=True, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text2_ru',
            field=models.TextField(default='Team', null=True, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text3',
            field=models.TextField(default='Company', verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text3_en',
            field=models.TextField(default='Company', null=True, verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text3_ru',
            field=models.TextField(default='Company', null=True, verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text4',
            field=models.TextField(default='Marketing', verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text4_en',
            field=models.TextField(default='Marketing', null=True, verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text4_ru',
            field=models.TextField(default='Marketing', null=True, verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text5',
            field=models.TextField(default='Bounty', verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text5_en',
            field=models.TextField(default='Bounty', null=True, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text5_ru',
            field=models.TextField(default='Bounty', null=True, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
    ]
