# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_auto_20171118_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfiguration',
            name='left_block_img2',
            field=models.ImageField(blank=True, upload_to='landing_images', verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u0435\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430'),
        ),
    ]
