# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_auto_20171123_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='adviser', verbose_name='\u0424\u043e\u0442\u043e')),
                ('name', models.CharField(max_length=128, verbose_name='\u0418\u043c\u044f')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f')),
                ('position', models.CharField(max_length=128, verbose_name='\u0420\u043e\u043b\u044c')),
                ('position_en', models.CharField(max_length=128, null=True, verbose_name='\u0420\u043e\u043b\u044c')),
                ('position_ru', models.CharField(max_length=128, null=True, verbose_name='\u0420\u043e\u043b\u044c')),
                ('linkedin', models.CharField(max_length=128, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Adviser',
                'verbose_name_plural': 'Adviser',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publication', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('title', models.TextField(verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('title_en', models.TextField(null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('title_ru', models.TextField(null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('announce', models.TextField(verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('announce_en', models.TextField(null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('announce_ru', models.TextField(null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('link', models.CharField(max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='team', verbose_name='\u0424\u043e\u0442\u043e')),
                ('name', models.CharField(max_length=128, verbose_name='\u0418\u043c\u044f')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='\u0418\u043c\u044f')),
                ('position', models.CharField(max_length=128, verbose_name='\u0420\u043e\u043b\u044c \u0432 \u043a\u043e\u043c\u0430\u043d\u0434\u0435')),
                ('position_en', models.CharField(max_length=128, null=True, verbose_name='\u0420\u043e\u043b\u044c \u0432 \u043a\u043e\u043c\u0430\u043d\u0434\u0435')),
                ('position_ru', models.CharField(max_length=128, null=True, verbose_name='\u0420\u043e\u043b\u044c \u0432 \u043a\u043e\u043c\u0430\u043d\u0434\u0435')),
                ('linkedin', models.CharField(max_length=128, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a',
                'verbose_name_plural': '\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_btn_text',
            field=models.CharField(default='Go to bounty page', max_length=32, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_btn_text_en',
            field=models.CharField(default='Go to bounty page', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_btn_text_ru',
            field=models.CharField(default='Go to bounty page', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_link',
            field=models.CharField(default='#', max_length=64, verbose_name='Bounty link'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_text',
            field=models.TextField(default='text', verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_text_en',
            field=models.TextField(default='text', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_text_ru',
            field=models.TextField(default='text', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_title',
            field=models.TextField(default='Bounty and referal programs', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_title_en',
            field=models.TextField(default='Bounty and referal programs', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='bounty_title_ru',
            field=models.TextField(default='Bounty and referal programs', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='publication_block_title',
            field=models.TextField(default='Publications', verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='publication_block_title_en',
            field=models.TextField(default='Publications', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='publication_block_title_ru',
            field=models.TextField(default='Publications', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'"),
        ),
    ]
