# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_auto_20171123_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=128, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('question_en', models.TextField(max_length=128, null=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('question_ru', models.TextField(max_length=128, null=True, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('answer', models.TextField(verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('answer_en', models.TextField(null=True, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('answer_ru', models.TextField(null=True, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441-\u041e\u0442\u0432\u0435\u0442',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b-\u041e\u0442\u0432\u0435\u0442\u044b',
            },
        ),
    ]
