# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_answerquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='facebook',
            field=models.CharField(blank=True, max_length=64, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='instagram',
            field=models.CharField(blank=True, max_length=64, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='linkedin',
            field=models.CharField(blank=True, max_length=64, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='medium',
            field=models.CharField(blank=True, max_length=64, verbose_name='Medium'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='reddit',
            field=models.CharField(blank=True, max_length=64, verbose_name='Reddit'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='slack',
            field=models.CharField(blank=True, max_length=64, verbose_name='Slack'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='twitter',
            field=models.CharField(blank=True, max_length=64, verbose_name='Twitter'),
        ),
    ]
