# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_auto_20171123_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='diagram_img',
            field=models.ImageField(blank=True, upload_to='sale_diagram', verbose_name='\u0414\u0438\u0430\u0433\u0440\u0430\u043c\u0430 \u0441\u043a\u0438\u0434\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='diagram_img_en',
            field=models.ImageField(blank=True, null=True, upload_to='sale_diagram', verbose_name='\u0414\u0438\u0430\u0433\u0440\u0430\u043c\u0430 \u0441\u043a\u0438\u0434\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='diagram_img_ru',
            field=models.ImageField(blank=True, null=True, upload_to='sale_diagram', verbose_name='\u0414\u0438\u0430\u0433\u0440\u0430\u043c\u0430 \u0441\u043a\u0438\u0434\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='emission_sale_text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='emission_sale_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='emission_sale_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='emission_sale_title',
            field=models.TextField(default='\u0421\u043a\u0438\u0434\u043a\u0438 \u0432\u043e \u0432\u0440\u0435\u043c\u044f \u044d\u043c\u0438\u0441\u0441\u0438\u0438', verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a '\u0421\u043a\u0438\u0434\u043a\u0430 \u0432\u043e \u0432\u0440\u0435\u043c\u044f \u044d\u043c\u0438\u0441\u0441\u0438\u0438'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='emission_sale_title_en',
            field=models.TextField(default='\u0421\u043a\u0438\u0434\u043a\u0438 \u0432\u043e \u0432\u0440\u0435\u043c\u044f \u044d\u043c\u0438\u0441\u0441\u0438\u0438', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a '\u0421\u043a\u0438\u0434\u043a\u0430 \u0432\u043e \u0432\u0440\u0435\u043c\u044f \u044d\u043c\u0438\u0441\u0441\u0438\u0438'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='emission_sale_title_ru',
            field=models.TextField(default='\u0421\u043a\u0438\u0434\u043a\u0438 \u0432\u043e \u0432\u0440\u0435\u043c\u044f \u044d\u043c\u0438\u0441\u0441\u0438\u0438', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a '\u0421\u043a\u0438\u0434\u043a\u0430 \u0432\u043e \u0432\u0440\u0435\u043c\u044f \u044d\u043c\u0438\u0441\u0441\u0438\u0438'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='ico_1',
            field=models.IntegerField(default='30', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 ICO \u0441\u043a\u0438\u0434\u043a\u0438 I \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='ico_2',
            field=models.IntegerField(default='25', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 ICO \u0441\u043a\u0438\u0434\u043a\u0438 II \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='ico_3',
            field=models.IntegerField(default='20', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 ICO \u0441\u043a\u0438\u0434\u043a\u0438 III \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='ico_4',
            field=models.IntegerField(default='15', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 ICO \u0441\u043a\u0438\u0434\u043a\u0438 IV \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='presale_1',
            field=models.IntegerField(default='50', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 Presale \u0441\u043a\u0438\u0434\u043a\u0438 I \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='presale_2',
            field=models.IntegerField(default='45', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 Presale \u0441\u043a\u0438\u0434\u043a\u0438 II \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='presale_3',
            field=models.IntegerField(default='40', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 Presale \u0441\u043a\u0438\u0434\u043a\u0438 III \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='presale_4',
            field=models.IntegerField(default='35', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 Presale \u0441\u043a\u0438\u0434\u043a\u0438 IV \u043f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='sale_bonus_text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='sale_bonus_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='sale_bonus_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='sale_bonus_title',
            field=models.TextField(default='\u0411\u043e\u043d\u0443\u0441\u044b \u0437\u0430 \u0440\u0430\u0437\u043c\u0435\u0440 \u043f\u043b\u0430\u0442\u0435\u0436\u0430', verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a '\u0411\u043e\u043d\u0443\u0441\u044b \u0437\u0430 \u0440\u0430\u0437\u043c\u0435\u0440 \u043f\u043b\u0430\u0442\u0435\u0436\u0430'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='sale_bonus_title_en',
            field=models.TextField(default='\u0411\u043e\u043d\u0443\u0441\u044b \u0437\u0430 \u0440\u0430\u0437\u043c\u0435\u0440 \u043f\u043b\u0430\u0442\u0435\u0436\u0430', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a '\u0411\u043e\u043d\u0443\u0441\u044b \u0437\u0430 \u0440\u0430\u0437\u043c\u0435\u0440 \u043f\u043b\u0430\u0442\u0435\u0436\u0430'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='sale_bonus_title_ru',
            field=models.TextField(default='\u0411\u043e\u043d\u0443\u0441\u044b \u0437\u0430 \u0440\u0430\u0437\u043c\u0435\u0440 \u043f\u043b\u0430\u0442\u0435\u0436\u0430', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a '\u0411\u043e\u043d\u0443\u0441\u044b \u0437\u0430 \u0440\u0430\u0437\u043c\u0435\u0440 \u043f\u043b\u0430\u0442\u0435\u0436\u0430'"),
        ),
    ]
