# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 13:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_auto_20171123_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingConfiguration2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_title', models.TextField(default='\u0423\u0441\u043b\u043e\u0432\u0438\u044f \u044d\u043c\u0438\u0441\u0441\u0438\u0438', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('emission_title_en', models.TextField(default='\u0423\u0441\u043b\u043e\u0432\u0438\u044f \u044d\u043c\u0438\u0441\u0441\u0438\u0438', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('emission_title_ru', models.TextField(default='\u0423\u0441\u043b\u043e\u0432\u0438\u044f \u044d\u043c\u0438\u0441\u0441\u0438\u0438', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('emission_text', models.TextField(default='\u0412 \u043f\u0435\u0440\u0438\u043e\u0434 \u044d\u043c\u0438\u0441\u0441\u0438\u0438...', verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c')),
                ('emission_text_en', models.TextField(default='\u0412 \u043f\u0435\u0440\u0438\u043e\u0434 \u044d\u043c\u0438\u0441\u0441\u0438\u0438...', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c')),
                ('emission_text_ru', models.TextField(default='\u0412 \u043f\u0435\u0440\u0438\u043e\u0434 \u044d\u043c\u0438\u0441\u0441\u0438\u0438...', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c')),
                ('token_presale_title', models.TextField(default='TOKEN PRESALE PHASE', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a TOKEN PRESALE')),
                ('token_presale_title_en', models.TextField(default='TOKEN PRESALE PHASE', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a TOKEN PRESALE')),
                ('token_presale_title_ru', models.TextField(default='TOKEN PRESALE PHASE', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a TOKEN PRESALE')),
                ('token_presale_text', ckeditor.fields.RichTextField(default='Start date...', verbose_name='\u0422\u0435\u043a\u0441\u0442 TOKEN PRESALE')),
                ('token_presale_text_en', ckeditor.fields.RichTextField(default='Start date...', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 TOKEN PRESALE')),
                ('token_presale_text_ru', ckeditor.fields.RichTextField(default='Start date...', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 TOKEN PRESALE')),
                ('token_sale_title', models.TextField(default='TOKEN SALE PHASE', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a TOKEN SALE')),
                ('token_sale_title_en', models.TextField(default='TOKEN SALE PHASE', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a TOKEN SALE')),
                ('token_sale_title_ru', models.TextField(default='TOKEN SALE PHASE', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a TOKEN SALE')),
                ('token_sale_text', ckeditor.fields.RichTextField(default='Start date...', verbose_name='\u0422\u0435\u043a\u0441\u0442 TOKEN SALE')),
                ('token_sale_text_en', ckeditor.fields.RichTextField(default='Start date...', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 TOKEN SALE')),
                ('token_sale_text_ru', ckeditor.fields.RichTextField(default='Start date...', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 TOKEN SALE')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430 \u0447.2',
            },
        ),
    ]
