# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_landingconfiguration2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043c\u0435\u043d\u044e \u0444\u0443\u0442\u0435\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043c\u0435\u043d\u044e \u0444\u0443\u0442\u0435\u0440\u0430',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043c\u0435\u043d\u044e \u0444\u0443\u0442\u0435\u0440\u0430',
            },
        ),
        migrations.CreateModel(
            name='FooterMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0441\u044b\u043b\u043a\u0438')),
                ('link', models.CharField(max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_items', to='config.FooterMenuCategory')),
            ],
            options={
                'verbose_name': '\u041f\u0443\u043d\u043a\u0442 \u043c\u0435\u043d\u044e \u0444\u0443\u0442\u0435\u0440\u0430',
                'verbose_name_plural': '\u041f\u0443\u043d\u043a\u0442 \u043c\u0435\u043d\u044e \u0444\u0443\u0442\u0435\u0440\u0430',
            },
        ),
    ]
