# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_footermenucategory_footermenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermenucategory',
            name='name_en',
            field=models.TextField(max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043c\u0435\u043d\u044e \u0444\u0443\u0442\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='footermenucategory',
            name='name_ru',
            field=models.TextField(max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043c\u0435\u043d\u044e \u0444\u0443\u0442\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='footermenuitem',
            name='name_en',
            field=models.TextField(max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0441\u044b\u043b\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='footermenuitem',
            name='name_ru',
            field=models.TextField(max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0441\u044b\u043b\u043a\u0438'),
        ),
    ]
