# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_auto_20171123_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration2',
            name='contract_link',
            field=models.TextField(default='#', verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 Smart contract'),
        ),
    ]
