# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_landingconfiguration2_contract_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='announce',
            field=models.TextField(blank=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='announce_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='announce_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='link',
            field=models.CharField(default='#', max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(default='#', max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
