# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_auto_20171124_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='left_block_img1_title',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='left_block_img1_title_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='left_block_img1_title_ru',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='left_block_img2',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='left_block_img2_title',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='left_block_img2_title_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='left_block_img2_title_ru',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='raised_text',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='raised_text_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='raised_text_ru',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='raised_value',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='right_block2_text',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='right_block2_text_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='right_block2_text_ru',
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='discount',
            field=models.TextField(default='40%', max_length=10, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='discount_end',
            field=models.TextField(default='\u041a\u043e\u043d\u0435\u0446 \u0441\u043a\u0438\u0434\u043a\u0438:', max_length=32, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u043b\u0435 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='discount_end_en',
            field=models.TextField(default='\u041a\u043e\u043d\u0435\u0446 \u0441\u043a\u0438\u0434\u043a\u0438:', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u043b\u0435 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='discount_end_ru',
            field=models.TextField(default='\u041a\u043e\u043d\u0435\u0446 \u0441\u043a\u0438\u0434\u043a\u0438:', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u043b\u0435 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='discount_info',
            field=models.TextField(default='\u0422\u0435\u043a\u0443\u0449\u0430\u044f \u0441\u043a\u0438\u0434\u043a\u0430:', max_length=32, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u043a\u0438\u0434\u043a\u043e\u0439'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='discount_info_en',
            field=models.TextField(default='\u0422\u0435\u043a\u0443\u0449\u0430\u044f \u0441\u043a\u0438\u0434\u043a\u0430:', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u043a\u0438\u0434\u043a\u043e\u0439'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='discount_info_ru',
            field=models.TextField(default='\u0422\u0435\u043a\u0443\u0449\u0430\u044f \u0441\u043a\u0438\u0434\u043a\u0430:', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u043a\u0438\u0434\u043a\u043e\u0439'),
        ),
    ]
