# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_auto_20171127_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_descr',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_descr_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_descr_ru',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_title',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_title_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_title_ru',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text1',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text1_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text1_ru',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text2',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text2_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text2_ru',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text3',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text3_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text3_ru',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text4',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text4_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration',
            name='exchange_triangle_text4_ru',
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_analytics_text',
            field=models.TextField(blank=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Analytics'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_analytics_text_en',
            field=models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Analytics'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_analytics_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Analytics'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_bottom_text',
            field=models.TextField(blank=True, verbose_name='\u041d\u0438\u0436\u043d\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_bottom_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u0438\u0436\u043d\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_bottom_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u0438\u0436\u043d\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_exchange_text',
            field=models.TextField(blank=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Exchange'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_exchange_text_en',
            field=models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Exchange'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_exchange_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Exchange'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_indices_text',
            field=models.TextField(blank=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Indices'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_indices_text_en',
            field=models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Indices'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_indices_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Indices'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_top_text',
            field=models.TextField(blank=True, verbose_name='\u0412\u0435\u0440\u0445\u043d\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_top_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0412\u0435\u0440\u0445\u043d\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='about_top_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0412\u0435\u0440\u0445\u043d\u0438\u0439 \u0442\u0435\u043a\u0441\u0442'),
        ),
    ]
