# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0030_auto_20171127_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='linkedin',
            field=models.CharField(blank=True, max_length=128, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='linkedin',
            field=models.CharField(blank=True, max_length=128, verbose_name='LinkedIn'),
        ),
    ]
