# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_auto_20171127_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration2',
            name='adviser_title',
            field=models.TextField(default='Advisers', verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Advisers'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='adviser_title_en',
            field=models.TextField(default='Advisers', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Advisers'"),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='adviser_title_ru',
            field=models.TextField(default='Advisers', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Advisers'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration2',
            name='team_title',
            field=models.TextField(default='\u041d\u0430\u0448\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u0430', verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041d\u0430\u0448\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u0430'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration2',
            name='team_title_en',
            field=models.TextField(default='\u041d\u0430\u0448\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u0430', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041d\u0430\u0448\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u0430'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration2',
            name='team_title_ru',
            field=models.TextField(default='\u041d\u0430\u0448\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u0430', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041d\u0430\u0448\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u0430'"),
        ),
    ]
