# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_auto_20171127_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration2',
            name='emission_text_right',
            field=models.TextField(default='\u0412 \u043f\u0435\u0440\u0438\u043e\u0434 \u044d\u043c\u0438\u0441\u0441\u0438\u0438...', verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c (\u0441\u043f\u0440\u0430\u0432\u0430)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='emission_text_right_en',
            field=models.TextField(default='\u0412 \u043f\u0435\u0440\u0438\u043e\u0434 \u044d\u043c\u0438\u0441\u0441\u0438\u0438...', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c (\u0441\u043f\u0440\u0430\u0432\u0430)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='emission_text_right_ru',
            field=models.TextField(default='\u0412 \u043f\u0435\u0440\u0438\u043e\u0434 \u044d\u043c\u0438\u0441\u0441\u0438\u0438...', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c (\u0441\u043f\u0440\u0430\u0432\u0430)'),
        ),
    ]
