# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_donationaddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='ruledbook_link',
            field=models.TextField(default='#!', verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 ruledbook'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='ruledbook_link_en',
            field=models.TextField(default='#!', null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 ruledbook'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='ruledbook_link_ru',
            field=models.TextField(default='#!', null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 ruledbook'),
        ),
    ]
