# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_landingconfiguration2_trading_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='video1_descr',
            field=models.TextField(blank=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='video1_descr_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='video1_descr_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='video1_link',
            field=models.TextField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043f\u0435\u0440\u0432\u043e\u0435 \u0432\u0438\u0434\u0435\u043e \u0441 \u0432\u043d\u0435\u0448\u043d\u0435\u0433\u043e \u0440\u0435\u0441\u0443\u0440\u0441\u0430'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='video2_descr',
            field=models.TextField(blank=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='video2_descr_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='video2_descr_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AddField(
            model_name='landingconfiguration',
            name='video2_link',
            field=models.TextField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0432\u0442\u043e\u0440\u043e\u0435 \u0432\u0438\u0434\u0435\u043e \u0441 \u0432\u043d\u0435\u0448\u043d\u0435\u0433\u043e \u0440\u0435\u0441\u0443\u0440\u0441\u0430'),
        ),
    ]
