# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0039_auto_20171204_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar1_bonus',
            field=models.TextField(default='+4,5%', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0431\u043e\u043d\u0443\u0441\u0430 ZNAQ (1)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar1_price',
            field=models.TextField(default='50', verbose_name='\u0421\u0443\u043c\u0430 \u043f\u043b\u0430\u0442\u0435\u0436\u0430 (1)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar1_total',
            field=models.TextField(default='52,25', verbose_name='\u0418\u0442\u043e\u0433\u043e\u0432\u0430\u044f \u0441\u0443\u043c\u043c\u0430 (1)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar2_bonus',
            field=models.TextField(default='+5%', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0431\u043e\u043d\u0443\u0441\u0430 ZNAQ (2)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar2_price',
            field=models.TextField(default='75', verbose_name='\u0421\u0443\u043c\u0430 \u043f\u043b\u0430\u0442\u0435\u0436\u0430 (2)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar2_total',
            field=models.TextField(default='78,55', verbose_name='\u0418\u0442\u043e\u0433\u043e\u0432\u0430\u044f \u0441\u0443\u043c\u043c\u0430 (2)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar3_bonus',
            field=models.TextField(default='+5,5%', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0431\u043e\u043d\u0443\u0441\u0430 ZNAQ (3)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar3_price',
            field=models.TextField(default='100', verbose_name='\u0421\u0443\u043c\u0430 \u043f\u043b\u0430\u0442\u0435\u0436\u0430 (3)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar3_total',
            field=models.TextField(default='105,5', verbose_name='\u0418\u0442\u043e\u0433\u043e\u0432\u0430\u044f \u0441\u0443\u043c\u043c\u0430 (3)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar4_bonus',
            field=models.TextField(default='+6%', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0431\u043e\u043d\u0443\u0441\u0430 ZNAQ (4)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar4_price',
            field=models.TextField(default='150', verbose_name='\u0421\u0443\u043c\u0430 \u043f\u043b\u0430\u0442\u0435\u0436\u0430 (4)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar4_total',
            field=models.TextField(default='159', verbose_name='\u0418\u0442\u043e\u0433\u043e\u0432\u0430\u044f \u0441\u0443\u043c\u043c\u0430 (4)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar5_bonus',
            field=models.TextField(default='+6,5%', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0431\u043e\u043d\u0443\u0441\u0430 ZNAQ (5)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar5_price',
            field=models.TextField(default='200', verbose_name='\u0421\u0443\u043c\u0430 \u043f\u043b\u0430\u0442\u0435\u0436\u0430 (5)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bar5_total',
            field=models.TextField(default='213', verbose_name='\u0418\u0442\u043e\u0433\u043e\u0432\u0430\u044f \u0441\u0443\u043c\u043c\u0430 (5)'),
        ),
    ]
