# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_auto_20171204_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date1',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (1)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date10',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (10)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date10_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (10)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date10_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (10)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date11',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (11)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date11_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (11)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date11_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (11)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date12',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (12)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date12_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (12)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date12_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (12)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date1_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (1)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (1)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date2',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (2)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (2)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (2)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date3',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (3)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date3_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (3)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date3_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (3)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date4',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (4)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date4_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (4)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date4_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (4)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date5',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (5)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date5_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (5)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date5_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (5)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date6',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (6)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date6_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (6)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date6_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (6)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date7',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (7)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date7_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (7)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date7_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (7)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date8',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (8)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date8_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (8)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date8_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (8)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date9',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (9)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date9_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (9)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_date9_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0434\u0430\u0442\u0430 (9)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text1',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (1)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text10',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (10)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text10_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (10)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text10_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (10)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text11',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (11)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text11_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (11)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text11_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (11)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text12',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (12)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text12_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (12)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text12_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (12)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text1_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (1)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (1)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text2',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (2)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (2)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (2)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text3',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (3)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text3_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (3)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text3_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (3)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text4',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (4)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text4_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (4)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text4_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (4)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text5',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (5)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text5_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (5)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text5_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (5)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text6',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (6)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text6_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (6)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text6_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (6)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text7',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (7)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text7_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (7)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text7_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (7)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text8',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (8)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text8_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (8)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text8_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (8)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text9',
            field=models.TextField(blank=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (9)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text9_en',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (9)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='road_text9_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Roadmap \u0442\u0435\u043a\u0441\u0442 (9)'),
        ),
    ]
