# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0041_auto_20171205_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bitcoin_talk_link',
            field=models.TextField(default='#', verbose_name='Bounty bitcoin talk'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='blogging_link',
            field=models.TextField(default='#', verbose_name='Bounty blogging'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='community_link',
            field=models.TextField(default='#', verbose_name='Bounty community'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='facebook_link',
            field=models.TextField(default='#', verbose_name='Bounty facebook'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='instagram_link',
            field=models.TextField(default='#', verbose_name='Bounty instagram'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='media_link',
            field=models.TextField(default='#', verbose_name='Bounty media'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='medium_link',
            field=models.TextField(default='#', verbose_name='Bounty medium'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='reddit_link',
            field=models.TextField(default='#', verbose_name='Bounty reddit'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='referral_link',
            field=models.TextField(default='#', verbose_name='Bounty referral'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='telegram_link',
            field=models.TextField(default='#', verbose_name='Bounty telegram'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='token_market_link',
            field=models.TextField(default='#', verbose_name='Bounty token market'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='twitter_link',
            field=models.TextField(default='#', verbose_name='Bounty twitter'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='youtube_link',
            field=models.TextField(default='#', verbose_name='Bounty youtube'),
        ),
    ]
