# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0042_auto_20171205_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bounty_subtitle',
            field=models.TextField(blank=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a bounty page'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bounty_subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a bounty page'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='bounty_subtitle_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a bounty page'),
        ),
    ]
