# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0043_auto_20171205_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfiguration',
            name='bounty_btn_text',
            field=models.CharField(default='\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u0411\u0430\u0443\u043d\u0442\u0438', max_length=32, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='bounty_btn_text_en',
            field=models.CharField(default='\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u0411\u0430\u0443\u043d\u0442\u0438', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='bounty_btn_text_ru',
            field=models.CharField(default='\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u0411\u0430\u0443\u043d\u0442\u0438', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='bounty_title',
            field=models.TextField(default='\u0411\u0430\u0443\u043d\u0442\u0438 \u0438 \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0440\u0430\u043c\u043c\u044b', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='bounty_title_en',
            field=models.TextField(default='\u0411\u0430\u0443\u043d\u0442\u0438 \u0438 \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0440\u0430\u043c\u043c\u044b', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='bounty_title_ru',
            field=models.TextField(default='\u0411\u0430\u0443\u043d\u0442\u0438 \u0438 \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u043e\u0440\u0430\u043c\u043c\u044b', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='exhibition_block_title',
            field=models.TextField(blank=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Exhibition'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='exhibition_block_title_en',
            field=models.TextField(blank=True, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Exhibition'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='exhibition_block_title_ru',
            field=models.TextField(blank=True, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Exhibition'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text2',
            field=models.TextField(default='\u041e\u0444\u0438\u0441\u043d\u044b\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b', verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text2_en',
            field=models.TextField(default='\u041e\u0444\u0438\u0441\u043d\u044b\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b', null=True, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text2_ru',
            field=models.TextField(default='\u041e\u0444\u0438\u0441\u043d\u044b\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b', null=True, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text5',
            field=models.TextField(default='\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0435', verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text5_en',
            field=models.TextField(default='\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0435', null=True, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='funds_text5_ru',
            field=models.TextField(default='\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0435', null=True, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='publication_block_title',
            field=models.TextField(default='\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438', verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='publication_block_title_en',
            field=models.TextField(default='\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='publication_block_title_ru',
            field=models.TextField(default='\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text2',
            field=models.TextField(default='\u041a\u043e\u043c\u0430\u043d\u0434\u0430', verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text2_en',
            field=models.TextField(default='\u041a\u043e\u043c\u0430\u043d\u0434\u0430', null=True, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text2_ru',
            field=models.TextField(default='\u041a\u043e\u043c\u0430\u043d\u0434\u0430', null=True, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text3',
            field=models.TextField(default='\u0418\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0430', verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text3_en',
            field=models.TextField(default='\u0418\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0430', null=True, verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text3_ru',
            field=models.TextField(default='\u0418\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u0430', null=True, verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text4',
            field=models.TextField(default='\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433', verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text4_en',
            field=models.TextField(default='\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433', null=True, verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text4_ru',
            field=models.TextField(default='\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433', null=True, verbose_name='\u0427\u0435\u0442\u0432\u0451\u0440\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text5',
            field=models.TextField(default='\u0411\u0430\u0443\u043d\u0442\u0438', verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text5_en',
            field=models.TextField(default='\u0411\u0430\u0443\u043d\u0442\u0438', null=True, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='tokens_text5_ru',
            field=models.TextField(default='\u0411\u0430\u0443\u043d\u0442\u0438', null=True, verbose_name='\u041f\u044f\u0442\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration2',
            name='adviser_title',
            field=models.TextField(default='\u0410\u0434\u0432\u0430\u0439\u0437\u0435\u0440\u044b', verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Advisers'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration2',
            name='adviser_title_en',
            field=models.TextField(default='\u0410\u0434\u0432\u0430\u0439\u0437\u0435\u0440\u044b', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Advisers'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration2',
            name='adviser_title_ru',
            field=models.TextField(default='\u0410\u0434\u0432\u0430\u0439\u0437\u0435\u0440\u044b', null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 'Advisers'"),
        ),
        migrations.AlterField(
            model_name='landingconfiguration2',
            name='token_presale_title',
            field=models.TextField(default='\u041f\u0440\u0435\u0434\u043f\u0440\u043e\u0434\u0430\u0436\u0430 \u0442\u043e\u043a\u0435\u043d\u043e\u0432', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a TOKEN PRESALE'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration2',
            name='token_presale_title_en',
            field=models.TextField(default='\u041f\u0440\u0435\u0434\u043f\u0440\u043e\u0434\u0430\u0436\u0430 \u0442\u043e\u043a\u0435\u043d\u043e\u0432', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a TOKEN PRESALE'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration2',
            name='token_presale_title_ru',
            field=models.TextField(default='\u041f\u0440\u0435\u0434\u043f\u0440\u043e\u0434\u0430\u0436\u0430 \u0442\u043e\u043a\u0435\u043d\u043e\u0432', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a TOKEN PRESALE'),
        ),
    ]
