# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0044_auto_20171206_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration2',
            name='token_sale_terms',
            field=models.TextField(blank=True, verbose_name='Token sale terms'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='token_sale_terms_en',
            field=models.TextField(blank=True, null=True, verbose_name='Token sale terms'),
        ),
        migrations.AddField(
            model_name='landingconfiguration2',
            name='token_sale_terms_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Token sale terms'),
        ),
    ]
