# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0046_landingconfiguration3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingconfiguration3',
            old_name='onepager_upload',
            new_name='rulebook',
        ),
        migrations.RenameField(
            model_name='landingconfiguration3',
            old_name='onepager_upload_en',
            new_name='rulebook_en',
        ),
        migrations.RenameField(
            model_name='landingconfiguration3',
            old_name='onepager_upload_ru',
            new_name='rulebook_ru',
        ),
    ]
