# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0047_auto_20171215_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footermenucategory',
            options={'ordering': ['order'], 'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043c\u0435\u043d\u044e \u0444\u0443\u0442\u0435\u0440\u0430', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043c\u0435\u043d\u044e \u0444\u0443\u0442\u0435\u0440\u0430'},
        ),
        migrations.AddField(
            model_name='footermenucategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='footermenuitem',
            name='open_new_tab',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043a\u0440\u044b\u0432\u0430\u0442\u044c \u0432 \u043d\u043e\u0432\u043e\u0439 \u0432\u043a\u043b\u0430\u0434\u043a\u0435'),
        ),
    ]
