# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0049_auto_20171221_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration3',
            name='title_bounty',
            field=models.TextField(default='ZNAQ | \u0411\u0430\u0443\u043d\u0442\u0438', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u0430\u0443\u043d\u0442\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0435)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='title_bounty_en',
            field=models.TextField(default='ZNAQ | \u0411\u0430\u0443\u043d\u0442\u0438', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u0430\u0443\u043d\u0442\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0435)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='title_bounty_ru',
            field=models.TextField(default='ZNAQ | \u0411\u0430\u0443\u043d\u0442\u0438', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u0430\u0443\u043d\u0442\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0435)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='title_landing',
            field=models.TextField(default='ZNAQ', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430 (\u0432 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0435)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='title_landing_en',
            field=models.TextField(default='ZNAQ', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430 (\u0432 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0435)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='title_landing_ru',
            field=models.TextField(default='ZNAQ', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430 (\u0432 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0435)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='title_lk',
            field=models.TextField(default='ZNAQ | \u041f\u0440\u043e\u0444\u0438\u043b\u044c', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043b\u0438\u0447\u043d\u043e\u0433\u043e \u043a\u0430\u0431\u0438\u043d\u0435\u0442\u0430 (\u0432 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0435)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='title_lk_en',
            field=models.TextField(default='ZNAQ | \u041f\u0440\u043e\u0444\u0438\u043b\u044c', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043b\u0438\u0447\u043d\u043e\u0433\u043e \u043a\u0430\u0431\u0438\u043d\u0435\u0442\u0430 (\u0432 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0435)'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='title_lk_ru',
            field=models.TextField(default='ZNAQ | \u041f\u0440\u043e\u0444\u0438\u043b\u044c', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043b\u0438\u0447\u043d\u043e\u0433\u043e \u043a\u0430\u0431\u0438\u043d\u0435\u0442\u0430 (\u0432 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0435)'),
        ),
    ]
