# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0050_auto_20171225_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration3',
            name='mockup',
            field=models.ImageField(blank=True, upload_to='mockups', verbose_name='Mockup image'),
        ),
    ]
