# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0051_landingconfiguration3_mockup'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration3',
            name='mockup_en',
            field=models.ImageField(blank=True, null=True, upload_to='mockups', verbose_name='Mockup image'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='mockup_ru',
            field=models.ImageField(blank=True, null=True, upload_to='mockups', verbose_name='Mockup image'),
        ),
    ]
