# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0055_donationaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_before_stage', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0431\u043b\u043e\u043a \u0434\u043e \u043d\u0430\u0447\u0430\u043b\u0430 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u0439?')),
                ('show_stage', models.BooleanField(default=False, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0431\u043b\u043e\u043a \u043f\u0440\u0438 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u044f\u0445?')),
                ('show_end_stage', models.BooleanField(default=False, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0431\u043b\u043e\u043a \u043f\u043e\u0441\u043b\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u0432\u0441\u0435\u0445 \u0441\u0442\u0430\u0434\u0438\u0439?')),
                ('before_start_title', models.TextField(default='\u0414\u043e \u043d\u0430\u0447\u0430\u043b\u0430 Pre-Sale \u043e\u0441\u0442\u0430\u043b\u043e\u0441\u044c:', verbose_name='\u0422\u0435\u043a\u0441\u0442-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043e \u043d\u0430\u0447\u0430\u043b\u0430 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u0439')),
                ('before_start_timer', models.DateField(default='2018-03-01', verbose_name='\u0422\u0430\u0439\u043c\u0435\u0440 \u0434\u043e \u043d\u0430\u0447\u0430\u043b\u0430 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u0439')),
                ('stage_title', models.TextField(default='\u0414\u043e \u043a\u043e\u043d\u0446\u0430 Pre-Sale \u043e\u0441\u0442\u0430\u043b\u043e\u0441\u044c:', verbose_name='\u0422\u0435\u043a\u0441\u0442-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0440\u0438 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u044f\u0445')),
                ('stage_timer', models.DateField(default='2018-03-01', verbose_name='\u0422\u0430\u0439\u043c\u0435\u0440 \u0434\u043e \u043a\u043e\u043d\u0446\u0430 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u0439')),
                ('stage_show_reised', models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c Reised?')),
                ('state_reised_text', models.CharField(default='Reised', max_length=32, verbose_name='\u0422\u0435\u043a\u0441\u0442 Reised/\u0421\u043e\u0431\u0440\u0430\u043d\u043e')),
                ('stage_reised_value', models.CharField(default='$ 10 357 456', max_length=32, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0441\u043e\u0431\u0440\u0430\u043d\u044b\u0445 \u0434\u0435\u043d\u0435\u0433')),
                ('stage_show_bottom_btn', models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443 \u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0435\u0439?')),
                ('stage_bottom_btn', models.TextField(default='\u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438\n\u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430', max_length=32, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c')),
                ('end_title', models.TextField(default='Pre-sale finished', verbose_name='\u0422\u0435\u043a\u0441\u0442-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u043b\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u0432\u0441\u0435\u0445 \u0441\u0442\u0430\u0434\u0438\u0439')),
                ('end_subtitle', models.TextField(default='Thank you for your contribution', verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u043b\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u0432\u0441\u0435\u0445 \u0441\u0442\u0430\u0434\u0438\u0439')),
                ('end_show_reised', models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c Reised?')),
                ('end_reised_text', models.CharField(default='Reised', max_length=32, verbose_name='\u0422\u0435\u043a\u0441\u0442 Reised/\u0421\u043e\u0431\u0440\u0430\u043d\u043e')),
                ('end_reised_value', models.CharField(default='$ 10 357 456', max_length=32, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0441\u043e\u0431\u0440\u0430\u043d\u044b\u0445 \u0434\u0435\u043d\u0435\u0433')),
                ('end_show_bottom_btn', models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443 \u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0435\u0439?')),
                ('end_bottom_btn', models.TextField(default='\u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438\n\u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430', max_length=32, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0434\u0438\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u0430 \u0434\u043b\u044f header \u043b\u0435\u043d\u0434\u0438\u043d\u0433\u0430',
            },
        ),
    ]
