# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0056_salestages'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestages',
            name='before_start_title_en',
            field=models.TextField(default='\u0414\u043e \u043d\u0430\u0447\u0430\u043b\u0430 Pre-Sale \u043e\u0441\u0442\u0430\u043b\u043e\u0441\u044c:', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043e \u043d\u0430\u0447\u0430\u043b\u0430 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='before_start_title_ru',
            field=models.TextField(default='\u0414\u043e \u043d\u0430\u0447\u0430\u043b\u0430 Pre-Sale \u043e\u0441\u0442\u0430\u043b\u043e\u0441\u044c:', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043e \u043d\u0430\u0447\u0430\u043b\u0430 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='end_bottom_btn_en',
            field=models.TextField(default='\u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438\n\u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='end_bottom_btn_ru',
            field=models.TextField(default='\u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438\n\u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='end_reised_text_en',
            field=models.CharField(default='Reised', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 Reised/\u0421\u043e\u0431\u0440\u0430\u043d\u043e'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='end_reised_text_ru',
            field=models.CharField(default='Reised', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 Reised/\u0421\u043e\u0431\u0440\u0430\u043d\u043e'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='end_subtitle_en',
            field=models.TextField(default='Thank you for your contribution', null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u043b\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u0432\u0441\u0435\u0445 \u0441\u0442\u0430\u0434\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='end_subtitle_ru',
            field=models.TextField(default='Thank you for your contribution', null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u043b\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u0432\u0441\u0435\u0445 \u0441\u0442\u0430\u0434\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='end_title_en',
            field=models.TextField(default='Pre-sale finished', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u043b\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u0432\u0441\u0435\u0445 \u0441\u0442\u0430\u0434\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='end_title_ru',
            field=models.TextField(default='Pre-sale finished', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u043b\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u0432\u0441\u0435\u0445 \u0441\u0442\u0430\u0434\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='stage_bottom_btn_en',
            field=models.TextField(default='\u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438\n\u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='stage_bottom_btn_ru',
            field=models.TextField(default='\u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438\n\u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430', max_length=32, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043d\u043e\u043f\u043a\u0438 \u043f\u043e\u0434 \u0442\u0430\u0439\u043c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='stage_title_en',
            field=models.TextField(default='\u0414\u043e \u043a\u043e\u043d\u0446\u0430 Pre-Sale \u043e\u0441\u0442\u0430\u043b\u043e\u0441\u044c:', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0440\u0438 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u044f\u0445'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='stage_title_ru',
            field=models.TextField(default='\u0414\u043e \u043a\u043e\u043d\u0446\u0430 Pre-Sale \u043e\u0441\u0442\u0430\u043b\u043e\u0441\u044c:', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442-\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0440\u0438 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u044f\u0445'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='state_reised_text_en',
            field=models.CharField(default='Reised', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 Reised/\u0421\u043e\u0431\u0440\u0430\u043d\u043e'),
        ),
        migrations.AddField(
            model_name='salestages',
            name='state_reised_text_ru',
            field=models.CharField(default='Reised', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 Reised/\u0421\u043e\u0431\u0440\u0430\u043d\u043e'),
        ),
    ]
