# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0057_auto_20180126_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestages',
            old_name='state_reised_text',
            new_name='stage_reised_text',
        ),
        migrations.RenameField(
            model_name='salestages',
            old_name='state_reised_text_en',
            new_name='stage_reised_text_en',
        ),
        migrations.RenameField(
            model_name='salestages',
            old_name='state_reised_text_ru',
            new_name='stage_reised_text_ru',
        ),
    ]
