# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0058_auto_20180126_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdsaleCurrencyIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_currency', models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0432\u0430\u043b\u044e\u0442\u0443?')),
                ('image', models.ImageField(upload_to='crownsale_img', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0432\u0430\u043b\u044e\u0442\u044b')),
                ('name', models.CharField(help_text='Bitcoin, Ripple etc.', max_length=64, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432\u0430\u043b\u044e\u0442\u044b')),
                ('value', models.CharField(help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: $ 12423', max_length=32, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('currency_type', models.CharField(choices=[('main', 'Main/\u041e\u0441\u043d\u043e\u0432\u043d\u0430\u044f'), ('other', 'Other/\u0414\u0440\u0443\u0433\u0430\u044f')], max_length=32, verbose_name='\u0422\u0438\u043f \u0432\u0430\u043b\u044e\u0442\u044b')),
            ],
            options={
                'verbose_name': "\u0412\u0430\u043b\u044e\u0442\u0430 \u0434\u043b\u044f \u043e\u043a\u043d\u0430 '\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438 \u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430'",
                'verbose_name_plural': "\u0412\u0430\u043b\u044e\u0442\u044b \u0434\u043b\u044f \u043e\u043a\u043d\u0430 '\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438 \u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430'",
            },
        ),
        migrations.CreateModel(
            name='CrowdsaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\u041f\u041e\u041a\u0410\u0417\u0410\u0422\u0415\u041b\u0418 \u041a\u0420\u0410\u0423\u0414\u0421\u0415\u0419\u041b\u0410', max_length=64, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u043f-\u0430\u043f\u0430 '\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438 \u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430'")),
                ('title_en', models.CharField(default='\u041f\u041e\u041a\u0410\u0417\u0410\u0422\u0415\u041b\u0418 \u041a\u0420\u0410\u0423\u0414\u0421\u0415\u0419\u041b\u0410', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u043f-\u0430\u043f\u0430 '\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438 \u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430'")),
                ('title_ru', models.CharField(default='\u041f\u041e\u041a\u0410\u0417\u0410\u0422\u0415\u041b\u0418 \u041a\u0420\u0410\u0423\u0414\u0421\u0415\u0419\u041b\u0410', max_length=64, null=True, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u043f-\u0430\u043f\u0430 '\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438 \u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430'")),
                ('total_text', models.CharField(default='Total', max_length=32, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Total'")),
                ('total_text_en', models.CharField(default='Total', max_length=32, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Total'")),
                ('total_text_ru', models.CharField(default='Total', max_length=32, null=True, verbose_name="\u0422\u0435\u043a\u0441\u0442 'Total'")),
                ('total_value', models.CharField(default='$ 11201', max_length=32, verbose_name="\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 'Total'")),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043f-\u0430\u043f \u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0435\u0439 \u043a\u0440\u0430\u0443\u0434\u0441\u0435\u0439\u043b\u0430',
            },
        ),
    ]
