# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0059_crowdsalecurrencyindex_crowdsaleinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsalecurrencyindex',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.CrowdsaleInfo'),
        ),
        migrations.AlterField(
            model_name='crowdsalecurrencyindex',
            name='value',
            field=models.CharField(help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: 1004 BTC', max_length=32, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
    ]
