# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0060_auto_20180126_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsalecurrencyindex',
            name='image',
            field=models.ImageField(upload_to='crowdsale_img', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0432\u0430\u043b\u044e\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='crowdsalecurrencyindex',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crowdsale_currencies', to='config.CrowdsaleInfo'),
        ),
    ]
