# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0061_auto_20180126_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdsalecurrencyindex',
            name='currency_type',
        ),
        migrations.AlterField(
            model_name='crowdsalecurrencyindex',
            name='image',
            field=models.ImageField(blank=True, upload_to='crowdsale_img', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0432\u0430\u043b\u044e\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='crowdsalecurrencyindex',
            name='show_currency',
            field=models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u044d\u0442\u043e\u0442 \u043f\u0443\u043d\u043a\u0442?'),
        ),
    ]
