# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0062_auto_20180201_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsalecurrencyindex',
            name='name_en',
            field=models.CharField(help_text='Bitcoin, Ripple, \u0414\u0440\u0443\u0433\u0438\u0435 \u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0446\u0438\u0438 etc.', max_length=64, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0443\u043d\u043a\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='crowdsalecurrencyindex',
            name='name_ru',
            field=models.CharField(help_text='Bitcoin, Ripple, \u0414\u0440\u0443\u0433\u0438\u0435 \u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0446\u0438\u0438 etc.', max_length=64, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0443\u043d\u043a\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='crowdsalecurrencyindex',
            name='name',
            field=models.CharField(help_text='Bitcoin, Ripple, \u0414\u0440\u0443\u0433\u0438\u0435 \u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0446\u0438\u0438 etc.', max_length=64, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0443\u043d\u043a\u0442\u0430'),
        ),
    ]
