# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0063_auto_20180201_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsalecurrencyindex',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a'),
        ),
    ]
