# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0065_partner_ratedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435/\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435/\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='ratedby',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435/\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='ratedby',
            name='name_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435/\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
