# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0068_auto_20180201_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='ratedby',
            name='link',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
