# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 15:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0069_auto_20180201_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration3',
            name='more_bounty_text',
            field=ckeditor.fields.RichTextField(default='More text...', verbose_name='More bounty modal text'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='more_bounty_text_en',
            field=ckeditor.fields.RichTextField(default='More text...', null=True, verbose_name='More bounty modal text'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='more_bounty_text_ru',
            field=ckeditor.fields.RichTextField(default='More text...', null=True, verbose_name='More bounty modal text'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='more_bounty_title',
            field=models.TextField(default='More title', verbose_name='More bounty modal title'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='more_bounty_title_en',
            field=models.TextField(default='More title', null=True, verbose_name='More bounty modal title'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='more_bounty_title_ru',
            field=models.TextField(default='More title', null=True, verbose_name='More bounty modal title'),
        ),
    ]
