# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0070_auto_20180207_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration',
            name='right_block_img3',
            field=models.ImageField(blank=True, upload_to='landing_images', verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u043f\u0440\u0430\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430'),
        ),
    ]
