# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 10:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0071_landingconfiguration_right_block_img3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingconfiguration3',
            name='medium_bounty_text',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration3',
            name='medium_bounty_text_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration3',
            name='medium_bounty_text_ru',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration3',
            name='medium_bounty_title',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration3',
            name='medium_bounty_title_en',
        ),
        migrations.RemoveField(
            model_name='landingconfiguration3',
            name='medium_bounty_title_ru',
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='linkedin_bounty_text',
            field=ckeditor.fields.RichTextField(default='To take part in the LinkedIn bounty campaign ...', verbose_name='LinkedIn bounty modal text'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='linkedin_bounty_text_en',
            field=ckeditor.fields.RichTextField(default='To take part in the LinkedIn bounty campaign ...', null=True, verbose_name='LinkedIn bounty modal text'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='linkedin_bounty_text_ru',
            field=ckeditor.fields.RichTextField(default='To take part in the LinkedIn bounty campaign ...', null=True, verbose_name='LinkedIn bounty modal text'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='linkedin_bounty_title',
            field=models.TextField(default='LinkedIn bounty', verbose_name='LinkedIn bounty modal title'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='linkedin_bounty_title_en',
            field=models.TextField(default='LinkedIn bounty', null=True, verbose_name='LinkedIn bounty modal title'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='linkedin_bounty_title_ru',
            field=models.TextField(default='LinkedIn bounty', null=True, verbose_name='LinkedIn bounty modal title'),
        ),
    ]
