# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0072_auto_20180208_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration3',
            name='bounty_top_text',
            field=models.TextField(default='Intro', verbose_name='Bounty page intro'),
        ),
    ]
