# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0073_landingconfiguration3_bounty_top_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration3',
            name='bounty_top_text_en',
            field=models.TextField(default='Intro', null=True, verbose_name='Bounty page intro'),
        ),
        migrations.AddField(
            model_name='landingconfiguration3',
            name='bounty_top_text_ru',
            field=models.TextField(default='Intro', null=True, verbose_name='Bounty page intro'),
        ),
    ]
