# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-15 14:31
from __future__ import unicode_literals

import config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0074_auto_20180208_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', config.models.CompressedImageField(upload_to='compressed', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
