# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0077_auto_20180219_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfiguration',
            name='discount_timer',
            field=models.DateTimeField(default='2017-12-31', verbose_name='\u0422\u0430\u0439\u043c\u0435\u0440 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='landingconfiguration',
            name='timer_sale',
            field=models.DateTimeField(default='2017-12-31', verbose_name='\u0422\u0430\u0439\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='salestages',
            name='before_start_timer',
            field=models.DateTimeField(default='2018-03-01', verbose_name='\u0422\u0430\u0439\u043c\u0435\u0440 \u0434\u043e \u043d\u0430\u0447\u0430\u043b\u0430 Presale/Sale \u0441\u0442\u0430\u0434\u0438\u0439'),
        ),
    ]
