# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0078_auto_20180219_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfiguration3',
            name='discount_rate',
            field=models.CharField(default='1.4', max_length=32, verbose_name='\u041a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442 \u0441\u043a\u0438\u0434\u043a\u0438 \u0434\u043b\u044f \u043a\u0430\u043b\u044c\u043a\u0443\u043b\u044f\u0442\u043e\u0440\u0430'),
        ),
    ]
