# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 18:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0081_auto_20180224_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_from_email', models.CharField(default='noreply@example.com', max_length=64, verbose_name='Email \u0441 \u043a\u043e\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u0441\u044b\u043b\u0430\u0442\u044c\u0441\u044f \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f')),
                ('subscribe_subject', models.TextField(default='ZNAQ News Subscription', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0435 \u043d\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438')),
                ('subscribe_subject_en', models.TextField(default='ZNAQ News Subscription', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0435 \u043d\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438')),
                ('subscribe_subject_ru', models.TextField(default='ZNAQ News Subscription', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0435 \u043d\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438')),
                ('subscribe_text', ckeditor.fields.RichTextField(default='You successfully subscribed!', verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0435 \u043d\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438')),
                ('subscribe_text_en', ckeditor.fields.RichTextField(default='You successfully subscribed!', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0435 \u043d\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438')),
                ('subscribe_text_ru', ckeditor.fields.RichTextField(default='You successfully subscribed!', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0435 \u043d\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0438')),
                ('register_subject', models.TextField(default='ZNAQ Registration', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('register_subject_en', models.TextField(default='ZNAQ Registration', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('register_subject_ru', models.TextField(default='ZNAQ Registration', null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('register_text', ckeditor.fields.RichTextField(default='You successfully registered!', verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('register_text_en', ckeditor.fields.RichTextField(default='You successfully registered!', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('register_text_ru', ckeditor.fields.RichTextField(default='You successfully registered!', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u044f \u043e \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 email \u043e\u043f\u043e\u0432\u0435\u0449\u0435\u043d\u0438\u0439',
            },
        ),
    ]
