# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 13:54
from __future__ import unicode_literals

import config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0083_auto_20180302_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_btn_text', models.CharField(default='Preview', max_length=32, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043d\u043e\u043f\u043a\u0438 Preview')),
                ('preview_btn_text_en', models.CharField(default='Preview', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043d\u043e\u043f\u043a\u0438 Preview')),
                ('preview_btn_text_ru', models.CharField(default='Preview', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043d\u043e\u043f\u043a\u0438 Preview')),
                ('preview_btn_link', models.URLField(default='#', verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 Preview')),
                ('show_preview', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443 Preview')),
                ('download_btn_text', models.CharField(default='Download (100 MB)', max_length=32, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043d\u043e\u043f\u043a\u0438 Download')),
                ('download_btn_text_en', models.CharField(default='Download (100 MB)', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043d\u043e\u043f\u043a\u0438 Download')),
                ('download_btn_text_ru', models.CharField(default='Download (100 MB)', max_length=32, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043d\u043e\u043f\u043a\u0438 Download')),
                ('download_btn_link', models.FileField(storage=config.models.OverwriteStorage(), upload_to='press_kit', verbose_name='\u0410\u0440\u0445\u0438\u0432 \u0434\u043b\u044f \u0441\u043a\u0430\u0447\u0438\u0432\u0430\u043d\u0438\u044f')),
                ('show_download', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443 Download')),
            ],
            options={
                'verbose_name': 'Press Kit',
            },
        ),
    ]
