# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0085_auto_20180308_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_terms', models.CharField(default='#!', max_length=64, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 Referral terms')),
                ('advertisement', models.CharField(default='#!', max_length=64, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 Advertisement materials')),
                ('email', models.CharField(default='coop@znaq.org', max_length=64, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Referral Page Settings',
            },
        ),
    ]
