# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 15:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0086_referralsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsettings',
            name='advertisement_en',
            field=ckeditor.fields.RichTextField(default='Advertisement materials', null=True, verbose_name='Advertisement materials \u043d\u0430 \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='advertisement_ru',
            field=ckeditor.fields.RichTextField(default='Advertisement materials', null=True, verbose_name='Advertisement materials \u043d\u0430 \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='referral_terms_en',
            field=ckeditor.fields.RichTextField(default='Referral terms', null=True, verbose_name='Referral terms \u043d\u0430 \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='referral_terms_ru',
            field=ckeditor.fields.RichTextField(default='Referral terms', null=True, verbose_name='Referral terms \u043d\u0430 \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
        migrations.AlterField(
            model_name='referralsettings',
            name='advertisement',
            field=ckeditor.fields.RichTextField(default='Advertisement materials', verbose_name='Advertisement materials \u043d\u0430 \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
        migrations.AlterField(
            model_name='referralsettings',
            name='referral_terms',
            field=ckeditor.fields.RichTextField(default='Referral terms', verbose_name='Referral terms \u043d\u0430 \u0440\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
    ]
