# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email \u043f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0430'),
        ),
    ]
