# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440\u044b: #ico #subscribe #currency #about #exchange #roadmap #emission #takermaker #smartcontract #sales#bonus #bounty #team #blog #faq', max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
