# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20171117_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(blank=True, help_text='\u041f\u0440\u0438\u043c\u0435\u0440\u044b: #ico #subscribe #currency #about #exchange #roadmap #emission #takermaker #smartcontract #sales#bonus #bounty #team #blog #faq #contact-us', max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
