# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketcapHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(verbose_name='Timestamp')),
                ('date', models.DateField(verbose_name='Date')),
                ('month_number', models.IntegerField(verbose_name='Month number')),
                ('cap', models.DecimalField(decimal_places=7, max_digits=18, verbose_name='Marketcap')),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u043a\u0430\u043f\u0438\u0442\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u043a\u0430\u043f\u0438\u0442\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u0438',
            },
        ),
    ]
