# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcaphistory',
            name='cap',
            field=models.DecimalField(decimal_places=7, max_digits=18, verbose_name='Znaq index'),
        ),
    ]
