# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.SlugField(blank=True, max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
