# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180118_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='link',
            new_name='slug',
        ),
    ]
