# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20180118_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
