# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='slug',
            field=models.SlugField(help_text='wp, on, doc etc.', verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u043c\u0430\u044f \u0447\u0430\u0441\u0442\u044c \u0441\u0441\u044b\u043b\u043a\u0438 \u0432 \u0430\u0434\u0440\u0435\u0441\u043d\u043e\u0439 \u0441\u0442\u0440\u043e\u043a\u0435 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0430'),
        ),
    ]
