# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180226_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='link',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043a\u0443\u0434\u0430 \u0431\u0443\u0434\u0435\u0442 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043e \u043f\u0435\u0440\u0435\u043d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='slug',
            field=models.SlugField(help_text='wp, on, doc etc.', unique=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u043c\u0430\u044f \u0447\u0430\u0441\u0442\u044c \u0441\u0441\u044b\u043b\u043a\u0438 \u0432 \u0430\u0434\u0440\u0435\u0441\u043d\u043e\u0439 \u0441\u0442\u0440\u043e\u043a\u0435 \u0431\u0440\u0430\u0443\u0437\u0435\u0440\u0430'),
        ),
    ]
